version: "3.9"
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 8080:80
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    build: ./docker/php
    expose:
      - 9000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./tagcloud.sql:/docker-entrypoint-initdb.d/tagcloud.sql
      - ./db_data:/var/lib/mysql
